"""add_memory_enabled_to_users

Revision ID: 0c85c59fdcb8
Revises: 232d5393d7d5
Create Date: 2026-03-24 11:02:34.055241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c85c59fdcb8'
down_revision: Union[str, Sequence[str], None] = '232d5393d7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('memory_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'memory_enabled')
    # ### end Alembic commands ###
