"""add rag_categories and allowed_rag_categories

Revision ID: 168401860e8d
Revises: 25db96d7c5a3
Create Date: 2026-03-19 10:31:10.511483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168401860e8d'
down_revision: Union[str, Sequence[str], None] = '25db96d7c5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rag_categories_id'), 'rag_categories', ['id'], unique=False)
    op.add_column('users', sa.Column('allowed_rag_categories', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allowed_rag_categories')
    op.drop_index(op.f('ix_rag_categories_id'), table_name='rag_categories')
    op.drop_table('rag_categories')
    # ### end Alembic commands ###
