"""add trace_id to error_logs

Revision ID: 8ad4f00a94dc
Revises: 72a4b50e72dc
Create Date: 2026-04-01 15:35:34.286113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad4f00a94dc'
down_revision: Union[str, Sequence[str], None] = '72a4b50e72dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error_logs', sa.Column('trace_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error_logs', 'trace_id')
    # ### end Alembic commands ###
