"""add project system_prompt and rag_categories

Revision ID: c5619469dd40
Revises: a1b2c3d4e5f6
Create Date: 2026-03-30 14:42:51.059318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5619469dd40'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('rag_categories', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'rag_categories')
    op.drop_column('projects', 'system_prompt')
    # ### end Alembic commands ###
