"""add audit_logs table

Revision ID: d26a88a26a5e
Revises: eeb67c437d3d
Create Date: 2026-03-23 09:21:43.093853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26a88a26a5e'
down_revision: Union[str, Sequence[str], None] = 'eeb67c437d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_user_email', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.execute('DROP TABLE IF EXISTS tour_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_groups',
    sa.Column('category_major', sa.TEXT(), nullable=True),
    sa.Column('category_minor', sa.TEXT(), nullable=True),
    sa.Column('departure_date', sa.TEXT(), nullable=True),
    sa.Column('group_code', sa.TEXT(), nullable=True),
    sa.Column('group_name', sa.TEXT(), nullable=True),
    sa.Column('product_name', sa.TEXT(), nullable=True),
    sa.Column('trade_price', sa.TEXT(), nullable=True),
    sa.Column('direct_price', sa.TEXT(), nullable=True),
    sa.Column('total_seats', sa.TEXT(), nullable=True),
    sa.Column('reserved_seats', sa.TEXT(), nullable=True),
    sa.Column('enrolled', sa.TEXT(), nullable=True),
    sa.Column('available_seats', sa.TEXT(), nullable=True),
    sa.Column('confirmed_bookings', sa.TEXT(), nullable=True),
    sa.Column('tentative_bookings', sa.TEXT(), nullable=True),
    sa.Column('deposit', sa.TEXT(), nullable=True),
    sa.Column('flight', sa.TEXT(), nullable=True),
    sa.Column('entry_exit_point', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('group_type', sa.TEXT(), nullable=True),
    sa.Column('staff_notes', sa.TEXT(), nullable=True)
    )
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
