"""add api_keys table

Revision ID: eeb67c437d3d
Revises: 168401860e8d
Create Date: 2026-03-20 17:19:53.252970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb67c437d3d'
down_revision: Union[str, Sequence[str], None] = '168401860e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_key')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_groups',
    sa.Column('category_major', sa.TEXT(), nullable=True),
    sa.Column('category_minor', sa.TEXT(), nullable=True),
    sa.Column('departure_date', sa.TEXT(), nullable=True),
    sa.Column('group_code', sa.TEXT(), nullable=True),
    sa.Column('group_name', sa.TEXT(), nullable=True),
    sa.Column('product_name', sa.TEXT(), nullable=True),
    sa.Column('trade_price', sa.TEXT(), nullable=True),
    sa.Column('direct_price', sa.TEXT(), nullable=True),
    sa.Column('total_seats', sa.TEXT(), nullable=True),
    sa.Column('reserved_seats', sa.TEXT(), nullable=True),
    sa.Column('enrolled', sa.TEXT(), nullable=True),
    sa.Column('available_seats', sa.TEXT(), nullable=True),
    sa.Column('confirmed_bookings', sa.TEXT(), nullable=True),
    sa.Column('tentative_bookings', sa.TEXT(), nullable=True),
    sa.Column('deposit', sa.TEXT(), nullable=True),
    sa.Column('flight', sa.TEXT(), nullable=True),
    sa.Column('entry_exit_point', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('group_type', sa.TEXT(), nullable=True),
    sa.Column('staff_notes', sa.TEXT(), nullable=True)
    )
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
